[start]
command:/usr/local/opnsense/scripts/OPNsense/Zapret/zapret_service.sh start
parameters:
type:script
message:starting zapret2

[stop]
command:/usr/local/opnsense/scripts/OPNsense/Zapret/zapret_service.sh stop
parameters:
type:script
message:stopping zapret2

[restart]
command:/usr/local/opnsense/scripts/OPNsense/Zapret/zapret_service.sh restart
parameters:
type:script
message:restarting zapret2

[reconfigure]
command:/usr/local/opnsense/scripts/OPNsense/Zapret/zapret_service.sh reconfigure
parameters:
type:script
message:reconfiguring zapret2

[status]
command:/usr/local/opnsense/scripts/OPNsense/Zapret/zapret_service.sh status; exit 0
parameters:
type:script_output
message:zapret2 status

[blockcheck]
command:/usr/local/opnsense/scripts/OPNsense/Zapret/blockcheck.sh
parameters:%s
type:script_output
message:running blockcheck2 against domain

[testdomain]
command:/usr/local/opnsense/scripts/OPNsense/Zapret/test_domain.sh
parameters:%s
type:script_output
message:testing domain connectivity
